ingressRoute:
  dashboard:
    enabled: false
   
#ports:
#  web:
#    redirectTo: websecure
#  websecure:
#    tls:
#      enabled: true
  
resources: 
  requests:
    cpu: 10m
    memory: 100Mi
  limits:
    cpu: 20m
    memory: 200Mi
